// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class PercentageComponentComponent extends RichDeclarativeComponent {

  public PercentageComponentComponent() {
  }

  public String getLabel() {
    return (String) getAttributes().get("label");
  }

  public String getValue() {
    return (String) getAttributes().get("value");
  }



}
