// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class PercentageComponentTag extends RichDeclarativeComponentTag {

  public PercentageComponentTag() {
  }

  public String getComponentType() {
    return "component.PercentageComponentComponentType";
  }

  protected String getViewId() {
    return "/PercentageComponent.jsf";
  }

  protected RichDeclarativeComponent createComponent() {
    return new PercentageComponentComponent();
  }

  public void setLabel(ValueExpression label) {
    this._label = label;
  }

  public void setValue(ValueExpression value) {
    this._value = value;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_label != null)
      bean.setValueExpression(_LABEL_KEY, _label);
    if (_value != null)
      bean.setValueExpression(_VALUE_KEY, _value);
  }

  public void release() {
    super.release();
    _label = null;
    _value = null;
  }

  private ValueExpression _label;
  private ValueExpression _value;

  private static final PropertyKey _LABEL_KEY = PropertyKey.createPropertyKey("label");
  private static final PropertyKey _VALUE_KEY = PropertyKey.createPropertyKey("value");

}
